'use client';

import Link from 'next/link';
import { FormEvent, useEffect, useMemo, useState } from 'react';
import { getApiErrorMessage } from '@/lib/api-error';
import { authenticatedFetch, getAccessToken, hasSessionPermission } from '@/lib/auth-session';

type TeamMember = { id: string; firstName: string; lastName: string; email: string; role: string; status: string; createdAt: string };
type Invite = { name: string; email: string; role: string; password: string; clinicCode: string };
const blank = { firstName: '', lastName: '', email: '', password: '', role: 'receptionist' };
const roleLabel: Record<string, string> = { owner: 'مالك العيادة', admin: 'مدير', doctor: 'طبيب', receptionist: 'استقبال' };

function createTemporaryPassword() {
  const letters = 'ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz';
  const numbers = '23456789';
  const read = new Uint32Array(10); crypto.getRandomValues(read);
  return Array.from(read, (value, index) => index === 0 ? letters[value % letters.length] : index === 1 ? numbers[value % numbers.length] : `${letters}${numbers}`[value % (`${letters}${numbers}`).length]).join('');
}

export default function TeamPage() {
  const [team, setTeam] = useState<TeamMember[]>([]); const [form, setForm] = useState(blank); const [reset, setReset] = useState<{ id: string; password: string } | null>(null);
  const [invite, setInvite] = useState<Invite | null>(null); const [clinicCode, setClinicCode] = useState(''); const [error, setError] = useState(''); const [notice, setNotice] = useState(''); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [hydrated, setHydrated] = useState(false);
  const mayCreate = hydrated && hasSessionPermission('user:create'); const mayUpdate = hydrated && hasSessionPermission('user:update');
  const invitationText = useMemo(() => invite ? `مرحبًا ${invite.name}،\nتمت دعوتك إلى فريق عيادة ${invite.clinicCode}.\nالدور: ${roleLabel[invite.role] || invite.role}\nرمز العيادة: ${invite.clinicCode}\nالبريد: ${invite.email}\nكلمة المرور المؤقتة: ${invite.password}\nرابط الدخول: ${window.location.origin}/login\n\nيرجى تغيير كلمة المرور فور تسجيل الدخول وعدم مشاركتها مع أي شخص.` : '', [invite]);

  const load = async () => { if (!getAccessToken()) { window.location.replace('/login'); return; } setLoading(true); try { const [response, me] = await Promise.all([authenticatedFetch('/api/v1/users'), authenticatedFetch('/api/v1/users/me')]); if (!response.ok) throw new Error(await getApiErrorMessage(response, 'تعذر تحميل الفريق.')); if (me.ok) { const user = await me.json() as { organizationId: string }; const org = await authenticatedFetch(`/api/v1/organizations/${user.organizationId}`); if (org.ok) setClinicCode((await org.json() as { slug: string }).slug); } setTeam(await response.json() as TeamMember[]); } catch (requestError) { setError(requestError instanceof Error ? requestError.message : 'تعذر تحميل الفريق.'); } finally { setLoading(false); } };
  useEffect(() => { setHydrated(true); void load(); }, []);
  const create = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); setSaving(true); setError(''); setNotice(''); try { const response = await authenticatedFetch('/api/v1/users', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(form) }); if (!response.ok) throw new Error(await getApiErrorMessage(response, 'تعذر إضافة الموظف.')); const member = await response.json() as TeamMember; setTeam((current) => [...current, member]); setInvite({ name: `${member.firstName} ${member.lastName}`, email: member.email, role: member.role, password: form.password, clinicCode }); setForm(blank); setNotice('تم إنشاء الحساب. انسخ الدعوة وأرسلها عبر Gmail أو WhatsApp؛ لم نربط مزود بريد تلقائي بعد.'); } catch (requestError) { setError(requestError instanceof Error ? requestError.message : 'تعذر إضافة الموظف.'); } finally { setSaving(false); } };
  const setPassword = async () => { if (!reset) return; setSaving(true); setError(''); try { const response = await authenticatedFetch(`/api/v1/users/${reset.id}/password`, { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ password: reset.password }) }); if (!response.ok) throw new Error(await getApiErrorMessage(response, 'تعذر تعيين كلمة المرور.')); setReset(null); setNotice('تم تعيين كلمة مرور مؤقتة جديدة. أرسلها للموظف في قناة خاصة.'); } catch (requestError) { setError(requestError instanceof Error ? requestError.message : 'تعذر تعيين كلمة المرور.'); } finally { setSaving(false); } };
  const copyInvite = async () => { if (!invitationText) return; await navigator.clipboard.writeText(invitationText); setNotice('تم نسخ نص الدعوة.'); };
  return <main dir="rtl" className="min-h-screen bg-slate-50 px-4 py-10 text-slate-900"><section className="mx-auto max-w-5xl rounded-2xl bg-white p-6 shadow-sm ring-1 ring-slate-200 sm:p-8"><Link href="/dashboard" className="text-sm font-medium text-sky-700 hover:underline">العودة إلى لوحة التحكم ←</Link><div className="mt-4"><p className="text-sm font-semibold text-teal-700">فريق العيادة</p><h1 className="mt-1 text-3xl font-bold">إدارة وصول فريقك</h1><p className="mt-2 text-slate-600">المدير ومالك العيادة فقط يمكنهما إضافة أعضاء. الطبيب والاستقبال لا يمكنهما دعوة أحد.</p></div>{error && <p role="alert" className="mt-5 rounded-lg bg-red-50 p-3 text-red-700">{error}</p>}{notice && <p className="mt-5 rounded-lg bg-emerald-50 p-3 text-emerald-800">{notice}</p>}
  {mayCreate && <form onSubmit={create} className="mt-6 grid gap-3 rounded-xl bg-slate-50 p-4 sm:grid-cols-2"><h2 className="sm:col-span-2 text-lg font-bold">دعوة عضو للفريق</h2><p className="sm:col-span-2 text-sm text-slate-600">سيُنشأ الحساب فورًا. بعد الحفظ ستظهر رسالة دعوة جاهزة للنسخ والإرسال؛ البريد التلقائي يحتاج إعداد مزود إرسال مستقل.</p><label className="grid gap-1 text-sm font-medium">الاسم الأول<input required value={form.firstName} onChange={(event) => setForm({ ...form, firstName: event.target.value })} className="rounded-lg border p-2 font-normal" /></label><label className="grid gap-1 text-sm font-medium">اسم العائلة<input required value={form.lastName} onChange={(event) => setForm({ ...form, lastName: event.target.value })} className="rounded-lg border p-2 font-normal" /></label><label className="grid gap-1 text-sm font-medium">Gmail أو البريد المهني<input required type="email" dir="ltr" value={form.email} onChange={(event) => setForm({ ...form, email: event.target.value })} className="rounded-lg border p-2 font-normal" /></label><label className="grid gap-1 text-sm font-medium">الدور<select value={form.role} onChange={(event) => setForm({ ...form, role: event.target.value })} className="rounded-lg border p-2 font-normal"><option value="receptionist">استقبال — تسجيل ومواعيد فقط</option><option value="doctor">طبيب — سجل طبي ووصفات</option><option value="admin">مدير — تشغيل وفريق</option></select></label><label className="grid gap-1 text-sm font-medium sm:col-span-2">كلمة المرور المؤقتة<div className="flex gap-2"><input required type="text" autoComplete="off" minLength={6} pattern="[A-Za-z0-9]+" title="حروف إنجليزية وأرقام فقط، 6 خانات على الأقل، مع حرف ورقم." value={form.password} onChange={(event) => setForm({ ...form, password: event.target.value })} className="min-w-0 flex-1 rounded-lg border p-2 font-normal" /><button type="button" onClick={() => setForm({ ...form, password: createTemporaryPassword() })} className="rounded-lg border border-slate-300 px-3 text-sm font-semibold">إنشاء تلقائي</button></div><span className="text-xs font-normal text-slate-500">لا تُرسل كلمة المرور في مجموعة عامة. يمكن تغييرها لاحقًا من قائمة الفريق.</span></label><button disabled={saving} className="w-fit rounded-lg bg-teal-700 px-4 py-2 font-bold text-white hover:bg-teal-800 disabled:opacity-60">{saving ? 'جارٍ الإنشاء…' : 'إنشاء الدعوة'}</button></form>}
  {invite && <section className="mt-6 rounded-xl border border-sky-200 bg-sky-50 p-5"><h2 className="font-bold text-sky-950">الدعوة جاهزة للإرسال</h2><p className="mt-2 text-sm text-sky-900">كلمة المرور المؤقتة: <b dir="ltr">{invite.password}</b></p><pre className="mt-3 whitespace-pre-wrap rounded-lg bg-white p-4 text-sm text-slate-700">{invitationText}</pre><div className="mt-3 flex flex-wrap gap-3"><button type="button" onClick={() => void copyInvite()} className="rounded-lg bg-sky-700 px-4 py-2 text-sm font-bold text-white">نسخ الدعوة</button><a href={`mailto:${encodeURIComponent(invite.email)}?subject=${encodeURIComponent(`دعوة فريق عيادة ${invite.clinicCode}`)}&body=${encodeURIComponent(invitationText)}`} className="rounded-lg border border-sky-700 px-4 py-2 text-sm font-bold text-sky-800">فتح Gmail لإرسالها</a><button type="button" onClick={() => setInvite(null)} className="rounded-lg border border-slate-300 px-4 py-2 text-sm">إخفاء</button></div></section>}
  {reset && <section className="mt-6 rounded-xl border border-amber-200 bg-amber-50 p-4"><h2 className="font-bold text-amber-950">تعيين كلمة مرور مؤقتة</h2><div className="mt-3 flex flex-wrap gap-3"><input type="text" autoComplete="off" minLength={6} pattern="[A-Za-z0-9]+" placeholder="كلمة مرور مؤقتة جديدة" value={reset.password} onChange={(event) => setReset({ ...reset, password: event.target.value })} className="rounded-lg border border-amber-300 p-2" /><button type="button" onClick={() => setReset({ ...reset, password: createTemporaryPassword() })} className="rounded-lg border border-amber-400 px-3">إنشاء تلقائي</button><button type="button" disabled={saving || reset.password.length < 6} onClick={() => void setPassword()} className="rounded-lg bg-amber-700 px-4 py-2 font-bold text-white disabled:opacity-50">حفظ</button><button type="button" onClick={() => setReset(null)} className="rounded-lg border border-amber-400 px-4 py-2">إلغاء</button></div></section>}
  <div className="mt-6 overflow-hidden rounded-xl border border-slate-200"><div className="bg-slate-100 p-3 font-semibold">أعضاء الفريق</div>{loading ? <p className="p-4 text-slate-600">جارٍ التحميل…</p> : <ul>{team.map((member) => <li key={member.id} className="flex flex-wrap items-center justify-between gap-3 border-t p-4"><span><span className="font-medium">{member.firstName} {member.lastName}</span><span className="mr-2 text-sm text-slate-500" dir="ltr">{member.email}</span></span><span className="flex items-center gap-2"><span className="rounded-full bg-slate-100 px-3 py-1 text-sm">{roleLabel[member.role] || member.role} · {member.status}</span>{mayUpdate && <button type="button" onClick={() => setReset({ id: member.id, password: '' })} className="text-sm font-medium text-amber-800 hover:underline">تعيين كلمة مرور</button>}</span></li>)}</ul>}</div></section></main>;
}
