'use client';

import Link from 'next/link';
import { BrandMark } from '@/components/brand-mark';

export default function Home() {
  return (
    <main dir="rtl" className="min-h-screen overflow-hidden bg-slate-950 text-white"><div className="mx-auto max-w-6xl px-6 py-6"><header className="flex items-center justify-between"><BrandMark light /><Link href="/login" className="rounded-lg border border-white/20 px-4 py-2 text-sm font-semibold hover:bg-white/10">دخول النظام</Link></header><section className="grid items-center gap-12 py-20 lg:grid-cols-2"><div><p className="inline-flex rounded-full bg-teal-400/10 px-3 py-1 text-sm font-medium text-teal-200 ring-1 ring-teal-400/30">إدارة عيادتك بوضوح وخصوصية</p><h1 className="mt-6 text-5xl font-bold leading-tight tracking-tight sm:text-6xl">بيانات المرضى تتحول إلى قرارات أفضل.</h1><p className="mt-6 max-w-xl text-lg leading-8 text-slate-300">Clinico يجمع الاستقبال، سجل المرضى، نقل البيانات من CRM القديم، والجمهور التسويقي المبني على الموافقة في مساحة واحدة لكل مركز.</p><div className="mt-8 flex flex-wrap gap-3"><Link href="/login" className="rounded-lg bg-teal-400 px-5 py-3 font-bold text-slate-950 hover:bg-teal-300">ابدأ من مساحة عيادتك</Link><a href="#features" className="rounded-lg border border-white/20 px-5 py-3 font-semibold hover:bg-white/10">اكتشف المزايا</a></div></div><div className="rounded-3xl border border-white/10 bg-gradient-to-br from-slate-800 to-slate-900 p-7 shadow-2xl"><p className="text-sm font-semibold text-teal-300">نظرة سريعة</p><div className="mt-5 grid gap-4 sm:grid-cols-2"><div className="rounded-2xl bg-white/5 p-5"><p className="text-3xl font-bold">300K</p><p className="mt-1 text-sm text-slate-300">سجل قابل للنقل في ملف واحد</p></div><div className="rounded-2xl bg-white/5 p-5"><p className="text-3xl font-bold">100%</p><p className="mt-1 text-sm text-slate-300">عزل بيانات كل مركز</p></div><div className="rounded-2xl bg-white/5 p-5 sm:col-span-2"><p className="font-semibold">جمهور تسويقي مسؤول</p><p className="mt-1 text-sm text-slate-300">التصدير يشمل فقط المرضى ذوي الموافقة الصريحة.</p></div></div></div></section><section id="features" className="grid gap-4 pb-16 md:grid-cols-3"><div className="rounded-2xl bg-white p-6 text-slate-900"><p className="font-bold">استقبال سريع</p><p className="mt-2 text-sm leading-6 text-slate-600">سجل دخول منظم، رقم ملف تلقائي، وبحث فوري.</p></div><div className="rounded-2xl bg-white p-6 text-slate-900"><p className="font-bold">نقل بلا إدخال يدوي</p><p className="mt-2 text-sm leading-6 text-slate-600">استيراد قاعدة المرضى من CSV مع معاينة ومنع التكرار.</p></div><div className="rounded-2xl bg-white p-6 text-slate-900"><p className="font-bold">تحكم في الخصوصية</p><p className="mt-2 text-sm leading-6 text-slate-600">صلاحيات حسب الدور وفصل كامل بين المراكز.</p></div></section></div></main>
  );
}
