'use client';

import Link from 'next/link';
import { FormEvent, useEffect, useState } from 'react';

type Status = { connected: boolean; phoneNumberId?: string; businessAccountId?: string; isEnabled?: boolean; appointmentTemplate?: string; marketingTemplate?: string; templateLanguage?: string; reminderHoursBefore?: number; remindersEnabled?: boolean; lastError?: string };
export default function WhatsAppSettingsPage() {
  const api = process.env.NEXT_PUBLIC_API_URL ?? 'http://localhost:3001'; const token = typeof window === 'undefined' ? '' : localStorage.getItem('token') ?? '';
  const [status, setStatus] = useState<Status>({ connected: false }); const [message, setMessage] = useState(''); const [saving, setSaving] = useState(false);
  const load = async () => { const response = await fetch(`${api}/api/v1/whatsapp/connection`, { headers: { Authorization: `Bearer ${token}` } }); if (response.ok) setStatus(await response.json() as Status); };
  useEffect(() => { if (!token) location.replace('/login'); else void load(); }, []);
  const submit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); setSaving(true); setMessage(''); const form = new FormData(event.currentTarget); const accessToken = String(form.get('accessToken') ?? ''); const body = { phoneNumberId: String(form.get('phoneNumberId') ?? ''), businessAccountId: String(form.get('businessAccountId') ?? ''), ...(accessToken ? { accessToken } : {}), appointmentTemplate: String(form.get('appointmentTemplate') ?? '') || undefined, marketingTemplate: String(form.get('marketingTemplate') ?? '') || undefined, templateLanguage: String(form.get('templateLanguage') ?? 'ar'), reminderHoursBefore: Number(form.get('reminderHoursBefore') ?? 24), remindersEnabled: form.get('remindersEnabled') === 'on', isEnabled: form.get('isEnabled') === 'on' }; try { const response = await fetch(`${api}/api/v1/whatsapp/connection`, { method: 'POST', headers: { Authorization: `Bearer ${token}`, 'Content-Type': 'application/json' }, body: JSON.stringify(body) }); if (!response.ok) throw new Error(await response.text()); setMessage('تم حفظ إعدادات WhatsApp بأمان.'); await load(); } catch { setMessage('تعذر حفظ الإعدادات. راجع القيم والصلاحيات.'); } finally { setSaving(false); } };
  const disconnect = async () => { if (!confirm('فصل WhatsApp عن هذه العيادة؟')) return; await fetch(`${api}/api/v1/whatsapp/connection`, { method: 'DELETE', headers: { Authorization: `Bearer ${token}` } }); await load(); };
  return <main dir="rtl" className="min-h-screen bg-slate-50 px-4 py-10"><section className="mx-auto max-w-3xl rounded-2xl bg-white p-8 shadow-sm ring-1 ring-slate-200"><Link className="text-sky-700" href="/dashboard">العودة للوحة التحكم ←</Link><h1 className="mt-4 text-3xl font-bold text-slate-950">ربط WhatsApp Business</h1><p className="mt-2 text-slate-600">لكل عيادة رقم مستقل. التوكن لا يظهر ولا يُخزّن كنص مكشوف.</p><div className={`mt-5 rounded-lg p-4 ${status.connected ? 'bg-emerald-50 text-emerald-800' : 'bg-amber-50 text-amber-800'}`}>{status.connected ? `متصل · Phone Number ID: ${status.phoneNumberId}` : 'غير متصل'}{status.lastError ? ` · ${status.lastError}` : ''}</div>{message && <p className="mt-4 rounded-lg bg-sky-50 p-3 text-sky-800">{message}</p>}<form onSubmit={submit} className="mt-6 grid gap-4 sm:grid-cols-2"><label>Phone Number ID<input required name="phoneNumberId" defaultValue={status.phoneNumberId} className="mt-1 w-full rounded border p-2" /></label><label>WhatsApp Business Account ID<input required name="businessAccountId" defaultValue={status.businessAccountId} className="mt-1 w-full rounded border p-2" /></label><label className="sm:col-span-2">Access Token<input required type="password" name="accessToken" placeholder={status.connected ? 'أدخل توكن جديد فقط عند تغييره' : ''} className="mt-1 w-full rounded border p-2" /></label><label>قالب تذكير الموعد<input name="appointmentTemplate" defaultValue={status.appointmentTemplate} className="mt-1 w-full rounded border p-2" /></label><label>قالب التسويق<input name="marketingTemplate" defaultValue={status.marketingTemplate} className="mt-1 w-full rounded border p-2" /></label><label>لغة القالب<input name="templateLanguage" defaultValue={status.templateLanguage ?? 'ar'} className="mt-1 w-full rounded border p-2" /></label><label>التذكير قبل (ساعة)<input name="reminderHoursBefore" type="number" min="1" max="168" defaultValue={status.reminderHoursBefore ?? 24} className="mt-1 w-full rounded border p-2" /></label><label className="sm:col-span-2 flex gap-2"><input name="remindersEnabled" type="checkbox" defaultChecked={status.remindersEnabled} /> تفعيل تذكير المواعيد تلقائيًا</label><label className="sm:col-span-2 flex gap-2"><input name="isEnabled" type="checkbox" defaultChecked={status.isEnabled} /> تفعيل الإرسال بعد اختبار قالب معتمد</label><button disabled={saving} className="rounded bg-sky-700 px-4 py-2 font-bold text-white disabled:opacity-60">{saving ? 'جارٍ الحفظ…' : 'حفظ الإعدادات'}</button>{status.connected && <button type="button" onClick={() => void disconnect()} className="rounded border border-red-300 px-4 py-2 text-red-700">فصل الربط</button>}</form></section></main>;
}
